Fix bug displaying nil strings
Problem:

When a string was nil, we would get:
```
NoMethodError: undefined method `[]' for nil:NilClass
```

Solution:

Make sure we're only indexing on strings by adding a call to `to_s`.